<a href="https://colab.research.google.com/github/Chetan-Patil-52/5th-Sem/blob/main/ML_Algos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas openpyxl scikit-learn nltk

In [ ]:
import pandas as pd

# Load dataset
file_path = "/content/sample_data/train.xlsx"
df = pd.read_excel(file_path)

# Display the first few rows
df.head()


,Item ID,Sentiment,SentimentText
0,1,0,"@RailMinIndia My PNR is 8348062961, I am in wa..."
1,2,0,@sureshpprabhu @RailMinIndia AC not working in...
2,3,0,@RailMinIndia I'm traveling to chennai by trai...
3,4,5,@RailMinIndia irctc is not responding at the t...
4,5,7,@DRMbhopal @RailMinIndia @sanjaygupta2012 @drm...


In [ ]:
df.rename(columns={"YourColumnName1": "Item ID", "YourColumnName2": "Sentiment", "YourColumnName3": "SentimentText"}, inplace=True)


In [ ]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Download NLTK stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Load dataset from Google Colab location
file_path = "/content/sample_data/train.xlsx"
df = pd.read_excel(file_path)

# Display first few rows
df.head()


,Item ID,Sentiment,SentimentText
0,1,0,"@RailMinIndia My PNR is 8348062961, I am in wa..."
1,2,0,@sureshpprabhu @RailMinIndia AC not working in...
2,3,0,@RailMinIndia I'm traveling to chennai by trai...
3,4,5,@RailMinIndia irctc is not responding at the t...
4,5,7,@DRMbhopal @RailMinIndia @sanjaygupta2012 @drm...


In [ ]:
# Define tokenizer
tokenizer = RegexpTokenizer(r'\w+')

# Preprocessing function
def preprocess_text(text):
    text = str(text).lower()  # Convert to lowercase
    text = re.sub(r'http\S+', '', text)  # Remove URLs
    text = re.sub(r'@\w+', '', text)  # Remove @mentions
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove special characters
    tokens = tokenizer.tokenize(text)  # Tokenize words
    tokens = [word for word in tokens if word not in stopwords.words('english')]  # Remove stopwords
    return " ".join(tokens)

# Apply preprocessing
df['clean_text'] = df['SentimentText'].astype(str).apply(preprocess_text)

# Display cleaned text
df[['Sentiment', 'clean_text']].head()


,Sentiment,clean_text
0,0,pnr way water toilet mess everywhere coach ple...
1,0,ac working prayag lucknow intercity today depa...
2,0,im traveling chennai train coach berth dirtyso...
3,5,irctc responding time tatkal booking
4,7,matter notified concerned official


In [ ]:
# TF-IDF Vectorizer
vectorizer = TfidfVectorizer(max_features=5000)  # Limit features to 5000
X = vectorizer.fit_transform(df['clean_text'])  # Transform text
y = df['Sentiment']  # Target labels (0 or 1)

# Split dataset into Train & Test (80-20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Compute Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Compute Metrics for Each Class in Multiclass Classification
num_classes = cm.shape[0]  # Number of classes
class_specificity = []
class_sensitivity = []
class_npv = []

for i in range(num_classes):
    # Extract True Positives (TP), False Positives (FP), False Negatives (FN), True Negatives (TN) for each class
    tp = cm[i, i]
    fn = cm[i, :].sum() - tp
    fp = cm[:, i].sum() - tp
    tn = cm.sum() - (tp + fn + fp)

    # Compute Specificity, NPV, and Sensitivity (Recall)
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    npv = tn / (tn + fn) if (tn + fn) > 0 else 0
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0  # Same as recall

    class_specificity.append(specificity)
    class_npv.append(npv)
    class_sensitivity.append(sensitivity)

    print(f"\n📌 Class {i}:")
    print(f"🔹 Negative Predictive Value (NPV): {npv:.4f}")
    print(f"🔹 Sensitivity (Recall): {sensitivity:.4f}")
    print(f"🔹 Specificity: {specificity:.4f}")

# Print Standard Metrics
print(f"\n✅ Accuracy: {accuracy:.4f}")
print(f"✅ Precision: {precision:.4f}")
print(f"✅ Recall (Sensitivity): {recall:.4f}")
print(f"✅ F1 Score: {f1:.4f}")

# Print Detailed Classification Report
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred, digits=4))


Confusion Matrix:
 [[52  0  0  1  1  3  0  0]
 [ 5  1  0  1  1  7  1  0]
 [ 1  0  0  0  0  3  0  0]
 [ 3  0  0 12  0  7  1  0]
 [ 6  0  0  0 28  5  0  0]
 [ 5  0  0  0  0 63  2  0]
 [11  0  0  0  2 18 10  0]
 [ 3  0  0  0  2  8  2  9]]

📌 Class 0:
🔹 Negative Predictive Value (NPV): 0.9734
🔹 Sensitivity (Recall): 0.9123
🔹 Specificity: 0.8433

📌 Class 1:
🔹 Negative Predictive Value (NPV): 0.9451
🔹 Sensitivity (Recall): 0.0625
🔹 Specificity: 1.0000

📌 Class 2:
🔹 Negative Predictive Value (NPV): 0.9854
🔹 Sensitivity (Recall): 0.0000
🔹 Specificity: 1.0000

📌 Class 3:
🔹 Negative Predictive Value (NPV): 0.9577
🔹 Sensitivity (Recall): 0.5217
🔹 Specificity: 0.9920

📌 Class 4:
🔹 Negative Predictive Value (NPV): 0.9542
🔹 Sensitivity (Recall): 0.7179
🔹 Specificity: 0.9745

📌 Class 5:
🔹 Negative Predictive Value (NPV): 0.9563
🔹 Sensitivity (Recall): 0.9000
🔹 Specificity: 0.7500

📌 Class 6:
🔹 Negative Predictive Value (NPV): 0.8798
🔹 Sensitivity (Recall): 0.2439
🔹 Specificity: 0.9742

📌 Class 7:
🔹 N

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import numpy as np
import pandas as pd
import re
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Ensure necessary NLTK downloads
nltk.download('stopwords')

# Load dataset
file_path = "/content/sample_data/train.csv"
df = pd.read_csv(file_path, encoding='latin1')

# Initialize tokenizer
tokenizer = RegexpTokenizer(r'\w+')

# Text Preprocessing Function
def preprocess_text(text):
    text = str(text).lower()  # Convert to lowercase
    text = re.sub(r'http\S+', '', text)  # Remove URLs
    text = re.sub(r'@\w+', '', text)  # Remove @mentions
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove special characters
    tokens = tokenizer.tokenize(text)  # Tokenization
    tokens = [word for word in tokens if word not in stopwords.words('english')]  # Remove stopwords
    return " ".join(tokens)

# Apply text preprocessing
df['clean_text'] = df['SentimentText'].astype(str).apply(preprocess_text)

# Define features and labels
X = df['clean_text']
y = df['Sentiment']

# Convert text to numerical representation
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)

# Train Softmax Classifier (Logistic Regression for multiclass classification)
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)

# Compute Standard Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')  # Sensitivity
f1 = f1_score(y_test, y_pred, average='weighted')

# Compute Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Compute Additional Metrics
num_classes = cm.shape[0]  # Number of classes

specificities = []
npvs = []

for i in range(num_classes):
    # True Positives, False Positives, False Negatives, True Negatives for each class
    tp = cm[i, i]
    fp = cm[:, i].sum() - tp
    fn = cm[i, :].sum() - tp
    tn = cm.sum() - (tp + fp + fn)

    # Compute Specificity and Negative Predictive Value (NPV)
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    npv = tn / (tn + fn) if (tn + fn) > 0 else 0

    specificities.append(specificity)
    npvs.append(npv)

# Compute Macro Specificity and NPV
macro_specificity = np.mean(specificities)
macro_npv = np.mean(npvs)

# Print Standard Metrics
print("\n🟢 Model Used: Softmax Classifier (Multinomial Logistic Regression)")
print(f"\n✅ Accuracy: {accuracy:.4f}")
print(f"✅ Precision: {precision:.4f}")
print(f"✅ Recall (Sensitivity): {recall:.4f}")
print(f"✅ F1 Score: {f1:.4f}")

# Print Additional Metrics
print(f"\n🔹 Macro Negative Predictive Value (NPV): {macro_npv:.4f}")
print(f"🔹 Macro Specificity: {macro_specificity:.4f}")

# Print Detailed Classification Report
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred, digits=4))



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Confusion Matrix:
 [[48  0  0  1  1  1  6  0]
 [ 3  1  0  1  1  2  8  0]
 [ 1  0  0  0  0  3  0  0]
 [ 3  0  0 16  0  2  2  0]
 [ 4  0  0  0 31  3  1  0]
 [ 0  0  0  0  0 65  5  0]
 [ 2  0  0  0  1  5 33  0]
 [ 1  0  0  0  0  3  5 15]]

🟢 Model Used: Softmax Classifier (Multinomial Logistic Regression)

✅ Accuracy: 0.7628
✅ Precision: 0.7914
✅ Recall (Sensitivity): 0.7628
✅ F1 Score: 0.7419

🔹 Macro Negative Predictive Value (NPV): 0.9661
🔹 Macro Specificity: 0.9632

📊 Classification Report:
               precision    recall  f1-score   support

           0     0.7742    0.8421    0.8067        57
           1     1.0000    0.0625    0.1176        16
           2     0.0000    0.0000    0.0000         4
           3     0.8889    0.6957    0.7805        23
           4     0.9118    0.7949    0.8493        39
           5     0.7738    0.9286    0.8442        70
           6     0.5500    0.8049    0.6535        41
           7     1.0000    0.6250    0.7692        24

    accuracy  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/m